# Funding options for BridgeMod
# Support the project and our vision to bridge the gap between developers and modders

github: []
patreon: []
open_collective: []
ko_fi: []
tidelift: []
community_bridge: []
liberapay: []
issuehunt: []
otechie: []
custom: []
